version: '3.8'

services:
  phantomnet:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - phantomnet-data:/app/data
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  phantomnet-data: