[package]
name = "phantomnet-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.4"
ark-ff = "0.4"
ark-relations = "0.4"
ark-groth16 = "0.4"
ark-r1cs-std = "0.4"
ark-bn254 = "0.4"
rand = "0.8"

[[bin]]
name = "phantomnet-zk"
path = "src/main.rs"
