name: PhantomNet CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test PhantomNet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --workspace --all-targets --verbose

    - name: Clippy Linter
      run: cargo clippy --workspace --all-targets -- -D warnings

    - name: Format Check
      run: cargo fmt --all -- --check

    - name: Run Tests
      run: cargo test --workspace --verbose